### ISSUE TITLE
Tixati Integration not showing download progress

### ISSUE THREAD

**Issue by methos237** [SchizoDuckie/DuckieTV#539]
I have been updating from the source nightly, and have recently switched to Tixati.  I have turned on the Tixati web interface, and Duckie is able to connect successfully, but unlike utorrent, Duckie can't track the download progress, or even show that the download has been completed.  I've attached screenshots of my settings as well as the console.  Let me know if you need anything else, and thanks for the great work!  Also, this is for the Duckie Stand-alone.

![tixati1](https://cloud.githubusercontent.com/assets/5730632/9496217/44f42906-4bdd-11e5-8f29-9eac157639ce.jpg)
![tixati2](https://cloud.githubusercontent.com/assets/5730632/9496216/44f55b28-4bdd-11e5-819a-90149d65ab0c.jpg)
![tixati3](https://cloud.githubusercontent.com/assets/5730632/9496215/44ef8c52-4bdd-11e5-8c59-411b1f9cf725.jpg)
![tixati4](https://cloud.githubusercontent.com/assets/5730632/9496218/450016d0-4bdd-11e5-915e-7148d4e0442b.jpg)
![tixati5](https://cloud.githubusercontent.com/assets/5730632/9496214/44ebce64-4bdd-11e5-8d5e-eb495b508e6f.jpg)

**Comment by SchizoDuckie** [comment]
Thanks for the excellent report! It looks like there's a mismatch on the hash here, afairc Tixati had some special method to do this.

**Comment by SchizoDuckie** [comment]
@methos237 that should help. let me know if you find anything else :+1:

**Comment by garfield69** [comment]
improvement of sorts. 
now getting 
![image](https://cloud.githubusercontent.com/assets/6933240/9504499/0a5c3810-4c91-11e5-97c9-59b895095f60.png)

**Comment by SchizoDuckie** [comment]
@garfield69 pull again. i fixed that too

**Comment by garfield69** [comment]
I have, still getting a couple errors
![image](https://cloud.githubusercontent.com/assets/6933240/9505040/16b71384-4c94-11e5-8a7c-f0741215180c.png)

**Comment by SchizoDuckie** [comment]
hmm it looks like i botched up the merge after receiving @garfield69's edits. hold on.
