### ISSUE TITLE
Cannot save a backup on Android

### ISSUE THREAD

**Issue by knowair** [SchizoDuckie/DuckieTV#848]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
... Android

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
... Installed 20-02-2017 latest nightly
... Weirdly, when getting this info to report this I find that the info page lists it as 2017-01-23 - so I'm not sure if the "hydrated" updates or the manual install of the latest have worked

**What is your Operating System (Windows, Mac, Linux, Android)**
... Android 7.0

**Describe the problem you are having and steps to reproduce if available**
... I cannot save a backup. I press the backup button, it turns blue to download, but clicking the now blue button does not download anything

**Attach any DuckieTV statistics or Developer Console logs if available**
... sorry not sure how to get these on android

**Comment by knowair** [comment]
Not sure what use these will be!
[backup button green](https://drive.google.com/open?id=0B1tnEy5MV2e8SkZnOE11UmxNdW8) 
[Then blue](https://drive.google.com/open?id=0B1tnEy5MV2e8MzdpakNOZGxXR0E)
[info page top](https://drive.google.com/open?id=0B1tnEy5MV2e8ZmlUTGFBNWVuZGM)
[info page 2](https://drive.google.com/open?id=0B1tnEy5MV2e8NHJLVnNOV0wxQ1E)

**Comment by garfield69** [comment]
it does look like the android builds is borked someplace, https://github.com/DuckieTV/duckietv-builder/issues/5 is probably related to the external android nightly package claiming to be 20-02-2017, but internally the code appears to be from the 2017-01-23 release.     
As for the original issue of the backup not working on android, this will be investigated once the android nightly build is sorted.

**Comment by garfield69** [comment]
@knowair https://github.com/DuckieTV/duckietv-builder/issues/5 has been resolved so the android Nightly should now be built from the latest development source.    
Please download from https://github.com/DuckieTV/Nightlies/releases and let us know if you are able to use the *Settings/Backup* or not.   
Thanks.

**Comment by SchizoDuckie** [comment]
Verified that the update works, but the backup doesnt show yet. I'll look into it tonight.

**Comment by knowair** [comment]
fwiw, i get the same. Updates, yep all good (thanks v much). Backup, still not downloading.

**Comment by SchizoDuckie** [comment]
Should be working as of tonight. Will report test findings tomorrow.

**Comment by knowair** [comment]
Sorry to report, not working for me.
The green create backup button does not even change to the blue download button now.

**Comment by SchizoDuckie** [comment]
I changed that functionality so that it should serve it right away, still
not working for me either indeed.

Op 2 mrt. 2017 12:09 p.m. schreef "knowair" <notifications@github.com>:

**Comment by garfield69** [comment]
I found some issues with the backup with Nightly 20170302 on win7 and linux, which I resolved with https://github.com/SchizoDuckie/DuckieTV/issues/863      
The next build 20170303 should include 863. So I invite you to test android again once 20170303 is out.

**Comment by SchizoDuckie** [comment]
Thanks for testing. I reverted the patch because it doesn't work on android either and apparently this is a more complicated topic requiring android specific phonegap code.

References:

http://stackoverflow.com/questions/33076885/save-file-to-public-directory-using-cordova-filetransfer
http://stackoverflow.com/questions/6417055/download-files-and-store-them-locally-with-phonegap-jquery-mobile-android-and-io?noredirect=1&lq=1

But this all means that we're doing android-custom patches, something i'm a bit reluctant to do.

**Comment by knowair** [comment]
> But this all means that we're doing android-custom patches, something i'm a bit reluctant to do.

Don't blame you, and wouldn't expect you to go out of your way like that. 

IIRC you did say when you announced the Android port it would be for shits and giggles and would not be supported to the same extent as the main fork. So if this is that point where you draw the line I fully understand.

It's no deal breaker DTV is far to integrated in my life at this stage I will struggle on! 

Cheers

**Comment by SchizoDuckie** [comment]
> IIRC you did say when you announced the Android port it would be for shits and giggles and would not be supported to the same extent as the main fork. So if this is that point where you draw the line I fully understand.

Correct, but if I check how often it is used, a totally unexpected high number comes out imo. And I see why: having DuckieTV actually running on your Android TV or tablet is awesome.

**Comment by SchizoDuckie** [comment]
So, I fixed it :)
It requires you to give a new permission to save files to EXTERNAL_STORAGE, then the download action creates a nice DuckieTV folder on your SD card, and saves the backup there.

I also fixed some other android nitpicks like the splash screen no longer working. Enjoy :+1:

**Comment by SchizoDuckie** [comment]
I updated the release since I was just a couple of minutes too late for the nightly, you can grab the apk here, or use the hydration. (not sure how that works with the permissions upgrade though)

https://github.com/DuckieTV/Nightlies/releases/tag/nightly-201703040030

**Comment by garfield69** [comment]
May need to do something similar with the *choose a backup to load* button on the  *settings,backup* panel.    
On my win7 bluestacks android emulator, that button does not trigger any popups.

**Comment by SchizoDuckie** [comment]
It should use the same code right?

B.t.w. I was thinking of making a generic popup that shows the import file
button and progress instead of the 2 separate implementations we have now

Op 4 mrt. 2017 8:08 p.m. schreef "garfield69" <notifications@github.com>:

**Comment by garfield69** [comment]
um, well the imports (whether from the backup-import.html used by the *favourites-is-empty* panel, or the backup.html used by the *settings,backup-import* panel), begin by using the input type=file from the templates, and the click then calls the restore() function from the backupCtrl, so I don't think its the same as the process that initiates a backup which you changed to use the android modified download.js.

**Comment by garfield69** [comment]
in any case you might want to test it for yourself, since my android emulator is running android 4.4 and is not coping too well with the graphic and services demands of the current duckietv code, so I cant be sure it's not just me :-(

**Comment by SchizoDuckie** [comment]
Backup import works for me. It opens a file chooser dialog. Closing this issue.

**Comment by knowair** [comment]
Thank you this works great! But only with a fresh install. The "hydrated" update does not work as it does not request the new permission. In my case the new apk install over the top of the old one gave me a pretty generic error, [App not installed](https://drive.google.com/file/d/0B1tnEy5MV2e8UFhKS0NMdVVPSUU/view?usp=drivesdk) I removed and reinstalled it which worked!

**Comment by SchizoDuckie** [comment]
Correct, that's unfortunately the only way to request the new permissions.

Op 7 mrt. 2017 7:59 p.m. schreef "knowair" <notifications@github.com>:

**Comment by garfield69** [comment]
\o/ successfully running Remix OS off a USB stick. It a flavour of android Marshmallow.     
I can now properly test the DuckieTV android platform :-)
