### ISSUE TITLE
Same Episode Downloading Every 15 Minutes

### ISSUE THREAD

**Issue by BananimusPrime** [SchizoDuckie/DuckieTV#926]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
1.1.4

**What is your Operating System (Windows, Mac, Linux, Android)**
MacOS Sierra 10.12.3

**Describe the problem you are having and steps to reproduce if available**
Auto-Torrent is set to 15 minutes, and every 15 minutes it starts downloading the same episode over & over.

I use Hazel to automatically move the downloaded show out of my Downloads folder the second it finishes. Is this relevant? Does DuckieTV look for the file where it was downloaded and if it doesn't find it, it downloads it again?

**Comment by garfield69** [comment]
>I use Hazel to automatically move the downloaded show out of my Downloads folder the second it finishes. Is this relevant? Does DuckieTV look for the file where it was downloaded and if it doesn't find it, it downloads it again?      

The first thing to check is whether your *DuckieTV* is working properly without *Hazel*.     
You will want to check that DuckieTV is *marking* an episode in its database as *downloaded* once the episode's torrent has in fact complete its download.      

So I propose you *disable* or *pause* any relevant Hazel rules for your torrent download folder, and let DuckieTV go through a cycle of auto-downloading an episode.     

Use the Auto-download monitor to look for episodes that have a status of **torrent launched**, or **has torrent**, and click on the **info icon** for that episode, to open the the *episode's details* panel.      
![image](https://user-images.githubusercontent.com/6933240/28437796-0cac466e-6df0-11e7-8cbd-6fa6e506303d.png)

Monitor the *download progress* and check that when the download reaches 100%, the **mark this episode as downloaded** button changes to a green **marked as downloaded** .
![image](https://user-images.githubusercontent.com/6933240/28437874-516f340a-6df0-11e7-8ad7-87fd8c92e0e8.png)
![image](https://user-images.githubusercontent.com/6933240/28437904-6eab326c-6df0-11e7-8009-20036c488c5b.png)

If this **does not happen** then Hazel is not responsible, and there is a problem someplace else that needs investigating.     
If it **does happen**, then yes, Hazel is interfering by getting in too early to move the file. Does the Hazel rule options allow you to delay the moving of the file for a few seconds or more?

**Comment by BananimusPrime** [comment]
Thank you very much for that guidance, I'll be sure to try that. Not sure about delaying Hazel but that's another good option, I'll check when possible. 

A secondary question, I've enabled multiple torrent search engines, and the description says to customise additional search engines in the advanced options of the torrent settings. I can't for the life of me find any advanced options though, is this feature available in the standalone app?

Thanks again.

**Comment by garfield69** [comment]
>A secondary question, I've enabled multiple torrent search engines, and the description says to customise additional search engines in the advanced options of the torrent settings. I can't for the life of me find any advanced options though, is this feature available in the standalone app?       

Firstly, the *multi-search engines* option applies only to the **manual torrent dialog search**, it has not been implemented for the *auto-download* yet.      
Secondly, you can see which search engines are used in the multi-se torrent dialog by clicking on the **show advanced options** link on the dialog.      
![image](https://user-images.githubusercontent.com/6933240/28440647-4204283a-6dfb-11e7-8d01-1a7eada2703b.png)
And then you can toggle any of the SE you want to **use/not use** by clicking on  each SE button
![image](https://user-images.githubusercontent.com/6933240/28440732-adc73e4a-6dfb-11e7-96c0-b7dcbc2f4560.png)

**Comment by FallDownTheSystem** [comment]
Same thing happened to me, but I'm not using Hazel, no idea what that even is. I am using custom torrent site through Jackett though on version standalone 1.1.5. It seems that downloaded episodes do not get set as downloaded and I have to manually set them as downloaded or it can download different torrents of the same episode.

Torrent auto-stop is disabled, as I want it to leave them on for seeding, not sure if that makes a difference.

**Comment by garfield69** [comment]
@FallDownTheSystem  FYI Hazel is a Mac OsX file manager :-).      
Having the auto-stop disabled should not prevent the mark-as-downloaded from functioning, I just tested/doubled checked this on my win7 with DuckieTV connected to uTorrent via the WEBUI client.     
  
So what platform are you running your DuckieTV Nightly on, and which torrent host and version are you using, and which DuckieTV torrent client are you connected on?      

In general, as long as the torrent host is reporting to the DuckieTV client that the progress has reached exactly 100% then the mark-as-downloaded should work.      
We have had problems in the past where a client was told 99.99 !!!!       

On that thought, are you allowing your torrent host to download all the files within a torrent, or are you setting some as skip/don't download? It's possible some hosts might not report 100% complete in this situation.

**Comment by FallDownTheSystem** [comment]
DuckieTV is running on Windows 10, connected to ruTorrent 0.9.6/0.13.6. The progress reaches 100%, and all the files are being downloaded. It auto-downloads the torrents from IP Torrents, so not using magnet links. The rTorrent web client shows the file at a 100% as well.

I have it set to download anything from the past 2 days on my calendar. Furthermore, the auto-download monitor shows status downloaded for the torrent, but the specific episode does not get marked as downloaded on calendar.

Edit: I've just noticed the pairing of the mark as watched and downloaded in the misc settings. Not sure if it has an effect, but I'll disable this setting and see if spooky stuff keeps happening 😄 

Edit2: Looking through all the files, there is one torrent which I've stopped from downloading all the files, I doubt that would interfere somehow with the other shows and episodes from being marked as downloaded.

**Comment by garfield69** [comment]
I'll see if I can replicate this on my sandbox. But first I will need a copy of your DuckieTV settings. Could you visit the DuckieTV *About* page, scroll down to the *statistics* section, and click on the *Statistics* header, which will copy the settings to your clipboard. You can then *paste* it below. Thanks.

**Comment by FallDownTheSystem** [comment]
[
  {
    "name": "DuckieTV Web Based",
    "data": "201707210130"
  },
  {
    "name": "Current Date and Time",
    "data": "Thu, 27 Jul 2017 22:51:10 GMT"
  },
  {
    "name": "NWJS, Chromium",
    "data": "0.23.5 , 59.0.3071.115"
  },
  {
    "name": "UserAgent",
    "data": "DuckieTV-Standalone  Nightly v201707210130 Windows NT 10.0; Win64; x64"
  },
  {
    "name": "Platform, Vendor",
    "data": "Win32, Google Inc."
  },
  {
    "name": "Screen (width x height)",
    "data": "2195 x 1235"
  },
  {
    "name": "Default Search Engine",
    "data": "IP torrents [Jackett] (Enabled)"
  },
  {
    "name": "Default Torrent Client",
    "data": "rTorrent (Enabled and Connected to Host)"
  },
  {
    "name": "Auto Download Service",
    "data": "(Enabled and Active)"
  },
  {
    "name": "Last checked TraktTV for DB updates on",
    "data": "Thu, 27 Jul 2017 14:16:39 GMT"
  },
  {
    "name": "User Preferences on Local Storage",
    "data": "{\n  \"KickAssTorrents.mirror\": \"https://kat.cr\",\n  \"ThePirateBay.mirror\": \"https://thepiratebay.org/\",\n  \"application.language\": \"en_us\",\n  \"application.locale\": \"en_us\",\n  \"autodownload.minSeeders\": 50,\n  \"autodownload.period\": 2,\n  \"background-rotator.opacity\": \"0.4\",\n  \"main.viewmode\": \"todo\",\n  \"calendar.mode\": \"date\",\n  \"calendar.show-specials\": true,\n  \"calendar.show-downloaded\": true,\n  \"calendar.show-episode-numbers\": true,\n  \"calendar.startSunday\": false,\n  \"client.determinedlocale\": \"en_us\",\n  \"download.ratings\": true,\n  \"lastSync\": -1,\n  \"library.smallposters\": true,\n  \"library.seriesgrid\": true,\n  \"kc.always\": false,\n  \"qbittorrent.server\": \"http://localhost\",\n  \"qbittorrent.port\": 8080,\n  \"qbittorrent.use_auth\": true,\n  \"qbittorrent.username\": \"admin\",\n  \"qbittorrent.password\": \"*****\",\n  \"qbittorrent32plus.server\": \"http://localhost\",\n  \"qbittorrent32plus.port\": 8080,\n  \"qbittorrent32plus.use_auth\": true,\n  \"qbittorrent32plus.username\": \"admin\",\n  \"qbittorrent32plus.password\": \"*****\",\n  \"series.displaymode\": \"poster\",\n  \"storage.sync\": false,\n  \"sync.progress\": true,\n  \"tixati.server\": \"http://localhost\",\n  \"tixati.use_auth\": true,\n  \"tixati.port\": 8888,\n  \"tixati.username\": \"admin\",\n  \"tixati.password\": \"*****\",\n  \"topSites.enabled\": false,\n  \"topSites.mode\": \"onhover\",\n  \"torrenting.autodownload\": true,\n  \"torrenting.autostop\": false,\n  \"torrenting.autostop_all\": false,\n  \"torrenting.client\": \"rTorrent\",\n  \"torrenting.directory\": true,\n  \"torrenting.enabled\": true,\n  \"torrenting.progress\": true,\n  \"torrenting.searchprovider\": \"IP torrents\",\n  \"torrenting.searchquality\": \"1080p\",\n  \"torrenting.streaming\": true,\n  \"vuze.server\": \"http://localhost\",\n  \"vuze.port\": 9091,\n  \"vuze.use_auth\": true,\n  \"vuze.username\": \"vuze\",\n  \"vuze.password\": \"*****\",\n  \"transmission.server\": \"http://localhost\",\n  \"transmission.port\": 9091,\n  \"transmission.use_auth\": true,\n  \"transmission.username\": \"admin\",\n  \"transmission.password\": \"*****\",\n  \"trakttv.passwordHash\": \"*****\",\n  \"trakttv.sync\": false,\n  \"trakttv.username\": null,\n  \"utorrentwebui.server\": \"http://localhost\",\n  \"utorrentwebui.port\": 8080,\n  \"utorrentwebui.username\": \"admin\",\n  \"utorrentwebui.password\": \"*****\",\n  \"utorrentwebui.use_auth\": true,\n  \"deluge.server\": \"http://37.48.70.158\",\n  \"deluge.port\": 16070,\n  \"deluge.password\": \"*****\",\n  \"deluge.use_auth\": true,\n  \"subtitles.languages\": [\n    \"eng\"\n  ],\n  \"autodownload.lastrun\": 1501195515141,\n  \"transmission.path\": \"/transmission/rpc\",\n  \"vuze.path\": \"/transmission/rpc\",\n  \"autodownload.multiSE\": {\n    \"ThePirateBay\": true,\n    \"1337x\": true,\n    \"IsoHunt\": true,\n    \"KATcr\": true,\n    \"Nyaa\": true,\n    \"RarBG\": true,\n    \"ShowRSS\": true,\n    \"TorrentDownloads\": true,\n    \"TorrentZ2\": true,\n    \"Zooqle\": true,\n    \"EzTV.ag\": true,\n    \"Idope\": true,\n    \"LimeTorrents\": true,\n    \"SkyTorrents\": true,\n    \"KickAss\": true,\n    \"IP torrents\": true\n  },\n  \"rtorrent.server\": \"https://fdts.seedr.io\",\n  \"rtorrent.port\": 443,\n  \"rtorrent.path\": \"/RPC-fdts\",\n  \"autodownload.delay\": 15,\n  \"torrenting.min_seeders\": 5,\n  \"torrenting.min_seeders_enabled\": false,\n  \"episode.watched-downloaded.pairing\": false\n}"
  },
  {
    "name": "Other significant Local Storage keys",
    "data": "{\n  \"1.1.4TorrentHashListCleanup\": \"Sun Feb 19 2017 17:02:49 GMT+0200 (FLE Standard Time)\",\n  \"1.1.4cleanupOrphanedEpisodes\": \"Sun Feb 19 2017 16:58:58 GMT+0200 (FLE Standard Time)\",\n  \"1.1.4cleanupOrphanedSeasons\": \"Sun Feb 19 2017 17:02:48 GMT+0200 (FLE Standard Time)\",\n  \"1.1.4qBittorrentPre32\": \"Sun Feb 19 2017 16:51:38 GMT+0200 (FLE Standard Time)\",\n  \"1.1.4refresh\": \"Sun Feb 19 2017 17:35:07 GMT+0200 (FLE Standard Time)\",\n  \"1.1.4refreshTrendingCache\": \"Sun Feb 19 2017 16:51:38 GMT+0200 (FLE Standard Time)\",\n  \"1.1.4updateDelugeAuth\": \"Sun Feb 19 2017 16:51:38 GMT+0200 (FLE Standard Time)\",\n  \"1.1.4updateTransmissionPath\": \"Sun Feb 19 2017 16:51:38 GMT+0200 (FLE Standard Time)\",\n  \"1.1.5deleteSearchEngines\": \"Sat Jul 22 2017 00:23:45 GMT+0300 (FLE Daylight Time)\",\n  \"1.1.5fanartCleanup\": \"Sat Jul 22 2017 00:24:15 GMT+0300 (FLE Daylight Time)\",\n  \"1.1.5updateDelugeAuth\": \"Sat Jul 22 2017 00:23:45 GMT+0300 (FLE Daylight Time)\",\n  \"1.1.5updateTorrenting.min_seeders\": \"Sat Jul 22 2017 00:23:45 GMT+0300 (FLE Daylight Time)\",\n  \"1.1migration\": \"Fri Mar 04 2016 19:18:06 GMT+0200 (Eastern Europe Standard Time)\",\n  \"autobackup.lastrun\": \"1500758682000\",\n  \"database.version.Episodes\": \"13\",\n  \"database.version.Fanart\": \"1\",\n  \"database.version.Jackett\": \"2\",\n  \"database.version.Seasons\": \"6\",\n  \"database.version.Series\": \"15\",\n  \"database.version.WatchList\": \"1\",\n  \"database.version.WatchListObject\": \"1\",\n  \"fanart.bootstrapped\": \"1\",\n  \"github.lastupdatecheck\": \"1500672225894\",\n  \"install.notify\": \"1.1.4\",\n  \"runtime.event\": \"{\\\"reason\\\":\\\"chrome_update\\\"}\",\n  \"snr.lastFetched\": \"1501102804638\",\n  \"standalone.alwaysShowTray\": \"Y\",\n  \"standalone.closeSystray\": \"Y\",\n  \"standalone.minimizeSystray\": \"N\",\n  \"standalone.position\": \"{\\\"width\\\":1922,\\\"height\\\":1042,\\\"x\\\":0,\\\"y\\\":0,\\\"state\\\":\\\"normal\\\"}\",\n  \"standalone.startupMinimized\": \"N\",\n  \"standalone.trayColor\": \"-inverted\",\n  \"standalone.zoomlevel\": \"6\",\n  \"torrenting.client\": \"rTorrent\",\n  \"trackers.fallBackList\": \"&tr=udp://tracker.coppersurfer.tk:6969/announce&tr=udp://tracker.pirateparty.gr:6969/announce&tr=udp://tracker.mg64.net:6969/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://9.rarbg.com:2710/announce&tr=udp://tracker.opentrackr.org:1337/announce&tr=http://asnet.pw:2710/announce&tr=http://tracker.opentrackr.org:1337/announce&tr=udp://public.popcorn-tracker.org:6969/announce&tr=udp://tracker.internetwarriors.net:1337/announce&tr=http://tracker.internetwarriors.net:1337/announce&tr=udp://tracker1.xku.tv:6969/announce&tr=udp://tracker1.wasabii.com.tw:6969/announce&tr=udp://tracker.zer0day.to:1337/announce&tr=http://91.218.230.81:6969/announce&tr=udp://peerfect.org:6969/announce&tr=udp://open.facedatabg.net:6969/announce&tr=udp://mgtracker.org:6969/announce&tr=http://tracker.mg64.net:6881/announce&tr=http://mgtracker.org:6969/announce\",\n  \"trackers.lastFetched\": \"1500672225630\",\n  \"trakttv.lastupdated\": \"1501164999286\",\n  \"trakttv.lastupdated.trending\": \"1500672929213\",\n  \"upgrade.notify\": \"1.1.4\",\n  \"xem.lastFetched\": \"1501102804640\"\n}"
  },
  {
    "name": "DB Series",
    "data": 52
  },
  {
    "name": "DB Series Hidden From Calendar",
    "data": 0
  },
  {
    "name": "DB Seasons",
    "data": 277
  },
  {
    "name": "DB Episodes",
    "data": 3786
  },
  {
    "name": "DB Fanart",
    "data": 1798
  },
  {
    "name": "DB Jackett",
    "data": 1
  }
]

**Comment by garfield69** [comment]
So I set up my win7 DuckieTV Nightly to connect to my Ubuntu rTorrent 0.9.6/0.13.6.      
I turned off auto-stop, and set most settings as you have them.     
Once the DuckieTV auto-download launched an episode's .torrent from Demonoid to rTorrent, I entered that episode's details panel and watched the blue progress bar edge to 100%, at which point:    
- the mark-as-downloaded was set,     
- then I got the torrent-downloaded notification,     
- and the progress bar turned orange, to indicate that seeding was now in progress.     
In other words, a successful test.      

Which does not help you in the least :-(      
The implication is that your fdts.seedr flavour of rTorrent is slightly different from the https://github.com/rakshasa/rtorrent version, or something else is interfering someplace.     

>The progress reaches 100%       

Can I eliminate some basic assumptions with you.... Have you actually watched the progress bar of an episode from the episode's details panel, and seen it go from blue to orange?     
Do you get the *torrent dowloaded* notifications?      

> the auto-download monitor shows status downloaded for the torrent, but the specific episode does not get marked as downloaded on calendar.      

I checked the auto-download service and monitor code, and if the Auto-Download monitor is showing torrents as downloaded, then the corresponding episode **has been marked as downloaded**, since that is where the information comes from.     
If DuckieTV at the completion of the torrent did not auto-mark it as downloaded, then the only other way this could happened is if you have manually marked it yourself. :-)     

>I've just noticed the pairing of the mark as watched and downloaded in the misc settings. Not sure if it has an effect      

I can confirm that this should not have any impact, I tested this just now.


Have you looked at the DuckieTV console for any signs of errors?      
Use **F12** to open the *Development Tools* page, and click on the **console** to view the log. Note: you may need to turn on *Verbose* output to get all the messages
![image](https://user-images.githubusercontent.com/6933240/28698430-96acf424-7397-11e7-8f15-07e1cfc6b4db.png)
But ignore any messages that are bracketed violations, they are not relevant
![image](https://user-images.githubusercontent.com/6933240/28698522-22390870-7398-11e7-9233-96094e36a8e8.png)

**Comment by FallDownTheSystem** [comment]
I tried it now that I changed some settings and added a new show that aired today. It started the auto download, showed me the blue bar as it was downloading and turned orange when it was at a 100%, it stayed orange until I stopped the torrent (finished state), at which time it turned green. Although it seems you can still manually set the episode as downloaded, so the automatically downloaded and set as downloaded aren't the same. Also to answer your question, yes I've always gotten the torrent downloaded notifications.

I noticed there was some other weird stuff going on, the status in the auto-download monitor says "Magnet torrent" at first, even though it's not a magnet torrent, and the status doesn't seem to update straight away, I have to reopen the monitor view for the status to get updated.

Really the original problem was that it would download an episode twice, if the first search result changes, i.e. it downloads two different torrents of the same episode. I'm not sure if whatever I've done has fixed the issue or not, but I'll report back if it happens again. At least now I get the orange 100% bar showing up as the episode is downloaded.

**Comment by garfield69** [comment]
OK, I think I have just had an insight into what may be going on, and I hope the following will clarify some things for you.      
I get the feeling that you are under the impression that the *Auto-Download Monitor* (ADM) reflects the current state of torrent activity and episode status.     

But the ADM is just a window into what **work** the *Auto-Download Service* (ADS) has performed.      
So the ADS is launched every 15 minutes, and as it process all the episodes looking for torrents to send to your torrent-host, it updates the ADM with what it is doing, stating which episodes it will not process because they have already been downloaded (*downloaded*), which episodes it will not need to search for a torrent because it has one already (*has torrent*), and any torrents that were submitted this run (*torrent launched*), among other processing result messages.      

So the ADM episode status of *Downloaded* is not a reflection of the current state of the episode whose torrent has just completed downloading and is now seeding, but a snapshot of the status of the ADS at the time the service ran. The next ADM update will happen when the ADS runs in another 15 minutes time :-)      

The ADS is not responsible for keeping an eye out on the state of the torrents, or updating the progress bars, or marking the episodes as downloaded once the torrent is completed, that is performed by other Torrent Services which run in the background.

I hope that resolves any confusion.      

I am going to change the ADM banner to *Auto-Download Service Monitor* to hopefully make that distinction a little clearer ;-)

**Comment by garfield69** [comment]
>I noticed there was some other weird stuff going on, the status in the auto-download monitor says "Magnet torrent" at first, even though it's not a magnet torrent      

Really?      

I'm just wondering how many instances of DuckieTV are you running?       
Because if you were running say, the latest DuckieTV Nightly Standalone, and using a Chrome Browser Extension DuckieTV 1.1.4, then this would go a long way to explaining your problems....     

why?      

Because each instance of DuckieTV has it own working data space, active database, and settings.      

So you would have two separate versions of the Auto-Download Service (ADS) busy submitting torrents, and updating their own databases with the status of the episodes. The two would clash when their torrent searches find slightly different torrents for an episode that fits their criteria.      
And in some situations, only one of them would see that a torrent has finished and been removed, and the other would see that its episode needs a torrent to be submitted because it was not active during the earlier activity.      

Also, ADS on 1.1.4 does not handle .torrent files, so it's Auto-Download Service Monitor (ADSM) shows *Has Magnet* when looking up torrents on the client it is connected to, while the latest Nightly's ADS can handle both magnets and .torrents, so it's ADSM reports *Has Torrent* when looking torrents up on the client it is connected to.

**Comment by FallDownTheSystem** [comment]
I'm only running the standalone version. I used to run the chrome version, but deleted that when 1.1.5 came out, and I just checked to make sure it's not enabled.

Either way, I'm not going to discount the possibility of human error or me simply misunderstanding how the application works, but I am fairly convinced it downloaded two of the same episode from different releases without me even touching the app, but I could be wrong :D 

I'll keep an eye out for it downloading things twice or ADS / ADM reporting weird things. I have some experience with Angular, so if something does come up, I might try to debug it myself to better understand what's happening :P

Thanks for taking the time to try to figure this out.

**Comment by FallDownTheSystem** [comment]
Aaaaaand it's happened again :D 

Episode of Preacher, s02e07. PC running with DuckieTV on all night. It had downloaded the torrent automatically, ADM shows https://i.imgur.com/8iUCJxb.png

Torrent client shows orange bar at a 100%, web client agrees, yet the calendar does not show any bar, but other episodes from yesterday that were also automatically downloaded do show an orange bar in the calendar. Note, at this point it has not downloaded the same episode (from a different torrent) twice yet. 

I was curious what would happen if I restarted duckieTV, since ADM showed status as magnet torrent, and there was no orange bar in the calendar. Sure enough after restarting, ADS started downloading another torrent of the same episode, and this time the progress bar does show up on the calendar as well, and the status has changed from magnet torrent to downloaded.

The first torrent had started downloading over an hour ago, and finished within 2 minutes of the download starting. The PC does not go into any kind of sleep or hibernation mode.

Very interesting stuff.

**Comment by Js41637** [comment]
I feel bad for garfield trying to figure this out all on his own but none the less; 
![image](https://user-images.githubusercontent.com/6258213/28808743-d124d0fe-76c1-11e7-9def-fcc60be64365.png)

**Comment by garfield69** [comment]
Went back to check the translations files for the STATUSCODES, discovered that the *en_us* table had the wrong description, which I did not pick up during testing because I use British English *en_uk* ;-)     
*magnet torrent* should be *torrent launched*, which I've now corrected.       

Anyway, back at the symptoms at hand, it would seem that there are occasions when the torrent hash is not being saved in the episode's database record. This is supported by the calendar (and I bet the episodes details page as well) not showing the torrent progress, but DuckieTV's torrent client page showing progress (since it is just a mirror of the torrent host's activity).       
This eventually leads ADS in the next cycle to submit the torrent again.      

Gives me a place to start looking...

**Comment by garfield69** [comment]
First off, could you make sure that you have the *preserve log* and *show timestamps* set in your console log settings, which you access by using the *F12* key, clicking on the *console* tab, and clicking on the *cog* icon.
![image](https://user-images.githubusercontent.com/6933240/28809755-6c3a85c2-76d9-11e7-81f5-c4478cc534e4.png)
This prevents the log being flushed between soft-resets when DuckieTV is restarted internally (which happens, for instance, daily a few seconds after midnight).      
Close the settings by clicking on the *cog* icon again.

Then, the next time you spot this issue, open the console and filter for *Hash* and see if there are any of these messages in the log. The full text will look something like this:
`Hash <infoHash> not found for torrent <releaseName> in 5 tries.`
![image](https://user-images.githubusercontent.com/6933240/28809820-dd9b57d2-76d9-11e7-84d5-6cbee2a48753.png)
Take a screen capture and paste the results directly into the body of the box below.     
This will either eliminate or confirm a current theory i'm pursuing. Thanks.

**Comment by FallDownTheSystem** [comment]
Sure thing, I'll keep you posted.

**Comment by FallDownTheSystem** [comment]
I got it to more or less happen again, with a little twist.
It didn't download different torrents, but it did "start" the same one again, as the first time the status was not set as downloaded, and the progress bar did not appear in the calendar, but after restarting duckieTV, the progress bar did appear. The status is _torrent launched_ still.

Here's the twist. The calendar says season14e16, but the torrent it searched and downloaded is s13e16. Manually clicking find torrent for the episode also searches for s13e16, and if I actually try to find s14e16, it does not exist (granted I don't watch this show usually, so I have no clue what's happening here).

Filtering the console log by Hash does not show anything, regardless, here's what  it showed in the console with no filtering:
![](https://i.imgur.com/zWPrOpx.png)

and after restarting:
![](https://i.imgur.com/cqa0bxJ.png)

Really there was no difference. Here are the full logs: 
[logs.zip](https://github.com/SchizoDuckie/DuckieTV/files/1189569/logs.zip)

Edit: Wanted to point out that after restarting duckieTV yet again, it does **not** try to start the download again, as it did after the first restart, so it's not something that happens everytime.

**Comment by garfield69** [comment]
The messages about Xem are perfectly normal. We use theXem.de to make corrections to the searches when http://thetvdb.com/ episodes do not line up with the torrent scene.     
Intermittent events like the one you are reporting are difficult to diagnose, I will do some research in my next free time slot and see if I can come up with some debug output for the log that might shed some light into what is going on....      
My best guess so far is that its something to do with your very busy rTorrent seeder box and DuckieTV's attempts to keep up with all the torrent activity over https.

**Comment by FallDownTheSystem** [comment]
![](https://i.imgur.com/nJCUvc9.png)

Noticed the same behaviour today, like clock work, every 15 minutes it tries to download the exact same episode since it's not getting marked as downloaded.

Why is it that when the ADS downloads a torrent (or tells thet torrent service to download it) the episode will not get marked as downloaded, but manually using the find a torrent or using the 'Auto download' does? If I understood correctly it's not the ADM or ADS's responsibility to control the status of the torrent or episode, but I assume no matter which way an episode is downloaded or a way torrent was started, it should get marked as downloaded once it is downloaded.

**Comment by garfield69** [comment]
So I have added some debug logging, which I hope will start us on the way to highlighting what is going on. (this may need fine tuning as I review results).       
Please download the latest release at https://github.com/DuckieTV/Nightlies/releases/latest and then perform the following steps:       
1. from your currently active DuckieTV Nightly, turn off auto-download by visiting the *Settings, Auto-download torrents* sidepanel, and clicking on the *disable auto-downloading torrents* button.     
![image](https://user-images.githubusercontent.com/6933240/29096972-84f6bfb4-7ceb-11e7-8639-9127e0e9638f.png)
2. shutdown DuckieTV and install the latest Nightly
3. start DuckieTV and open the *Development Tools* page with the *F12* key and click on the *Console* tab to view the log.     
    First off, could you make sure that you have the *preserve log* and *show timestamps* set in your console log settings, which you access by clicking on the *cog* icon.    
    ![image](https://user-images.githubusercontent.com/6933240/28809755-6c3a85c2-76d9-11e7-81f5-c4478cc534e4.png)
    This prevents the log being flushed between soft-resets when DuckieTV is restarted internally (which happens, for instance, daily a few seconds after midnight).      
Close the settings by clicking on the *cog* icon again.    
4. at the `>` prompt paste the following `localStorage.setItem('debug926', 'true')` and press the *enter* key.
5. shutdown DuckieTV and start it up again.
6. enable the auto-download service.
7. Avoid shutting down DuckieTV if you can, and **when the problem resurfaces**, then       
8. make sure that the *filter* is empty and the *logging* is set to *all-levels*, then right-click over one the left hand side if the log and use the *save-as* to dump the log to a file. Please *ZIP* the file and drag&drop it in the empty box below.
![image](https://user-images.githubusercontent.com/6933240/29097433-e02ea98a-7ced-11e7-8342-175b6d901781.png)
9. if you want to stop debugging, then use the following `localStorage.removeItem('debug926')` and restart DuckieTV to switch it off.       
Thanks.

**Comment by Scientist07** [comment]
[DuckieTv logs.zip](https://github.com/SchizoDuckie/DuckieTV/files/1235786/DuckieTv.logs.zip) 

Attached are the logs I was asked to provide from this reddit thread: https://www.reddit.com/r/duckietv/comments/6u7smq/duckie_tv_calendar_bug/  

The logs start at around 12:30 pm today (GMT -4) because unfortunately electricity went at my house. Log 1 was taken around 1:30 pm and log 2 around 5 hrs later at 6:30 pm.

**Comment by garfield69** [comment]
Excellent. The logs provided enough information that I was able to reproduce the problem on my sandbox. Now I just have to figure out what is really going on.

**Comment by garfield69** [comment]
I believe I've fixed the problem, and have tested it on my sandbox successfully.      
@FallDownTheSystem  and @Scientist07  Grab the next Nightly at https://github.com/DuckieTV/Nightlies/releases/latest when it comes out in about 21 hours from now and please confirm that it is working for you. Thanks.

**Comment by Scientist07** [comment]
When I got this message I Immediately went to download the latest nightly but the problem still existed. Then I noticed you said "21 hrs from now" and realized this build wasn't the one you were talking about. I got this build v201708190130 but have now noticed there is a newer one that came out an hr ago (GMT -4). Will install and report back.

**Comment by garfield69** [comment]
testing complete as per https://www.reddit.com/r/duckietv/comments/6u7smq/duckie_tv_calendar_bug/dlvng72/
